# fly.toml app configuration
app = "niyantran-instruments"
primary_region = "bom"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "4000"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.status]
    type = "http"
    interval = "30s"
    timeout = "5s"
    grace_period = "5s"
    method = "get"
    path = "/api/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
